In [1]:
print("Hello MediRAG")

Hello MediRAG

In [2]:
import pandas as pd
print(pd.__version__)

3.0.5

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/raw/healthcare_rag_dataset.csv")

In [5]:
df.head()

,doc_id,title,category,icd10_code,document_type,content_text,symptoms,treatments,risk_factors,prevention,...,is_contagious,target_audience,language,source_name,source_url,last_updated,word_count,reading_level_score,evidence_level,review_status
0,DOC-E6C0C42D,Conjunctivitis (Pink Eye) - Symptom Guide,Ophthalmologic,H10,Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub...",...,Yes,Patient Education,en,CDC - Conjunctivitis,https://www.cdc.gov/conjunctivitis/index.html,2025-11-05,45,7.1,C,Peer-Reviewed
1,DOC-044236DE,Urinary Tract Infection - Clinical Decision Su...,Infectious,N39,Clinical Summary,Clinical decision support summary for Urinary ...,"Strong, persistent urge to urinate; burning se...","Short course of antibiotics (e.g., nitrofurant...",Female anatomy; sexual activity; certain types...,"Adequate hydration, urinating after intercours...",...,No,Clinician,en,NIDDK - Urinary Tract Infections,https://www.niddk.nih.gov/health-information/u...,2024-05-29,75,18.0,A,Peer-Reviewed
2,DOC-FDAC856F,What are the common symptoms of Major Depressi...,Mental Health,F32,FAQ,Q: What are the common symptoms of Major Depre...,Persistent sad or empty mood; loss of interest...,"Psychotherapy (cognitive behavioral therapy, i...",Family history of depression; history of traum...,"Stress management, strong social support netwo...",...,No,General Public,en,NIMH - Depression,https://www.nimh.nih.gov/health/topics/depression,2024-05-08,42,8.0,C,Peer-Reviewed
3,DOC-79AD337F,Is Essential Hypertension contagious?,Cardiovascular,I10,FAQ,Q: Is Essential Hypertension contagious? A: Ba...,Often asymptomatic; occasional headaches; shor...,"Lifestyle changes (DASH diet, sodium reduction...",High sodium intake; obesity; sedentary lifesty...,"Reducing dietary sodium, maintaining healthy w...",...,No,Patient Education,en,American Heart Association - High Blood Pressure,https://www.heart.org/en/health-topics/high-bl...,2027-03-09,22,8.9,C,Peer-Reviewed
4,DOC-90A8B2C8,What is Psoriasis?,Dermatologic,L40,FAQ,Q: What is Psoriasis? A: Psoriasis is a chroni...,"Red patches of skin covered with thick, silver...","Topical treatments (corticosteroids, vitamin D...",Family history of psoriasis; smoking; obesity;...,No definitive prevention exists; managing trig...,...,No,General Public,en,CDC - Psoriasis,https://www.cdc.gov/psoriasis/index.html,2025-07-15,34,9.8,B,Peer-Reviewed

In [6]:
df.shape

(409, 23)

In [7]:
df.columns

Index(['doc_id', 'title', 'category', 'icd10_code', 'document_type',
       'content_text', 'symptoms', 'treatments', 'risk_factors', 'prevention',
       'common_age_group', 'severity_level', 'is_chronic', 'is_contagious',
       'target_audience', 'language', 'source_name', 'source_url',
       'last_updated', 'word_count', 'reading_level_score', 'evidence_level',
       'review_status'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   doc_id               409 non-null    str
 1   title                409 non-null    str
 2   category             409 non-null    str
 3   icd10_code           409 non-null    str
 4   document_type        409 non-null    str
 5   content_text         409 non-null    str
 6   symptoms             409 non-null    str
 7   treatments           409 non-null    str
 8   risk_factors         409 non-null    str
 9   prevention           409 non-null    str
 10  common_age_group     409 non-null    str
 11  severity_level       409 non-null    str
 12  is_chronic           409 non-null    str
 13  is_contagious        409 non-null    str
 14  target_audience      409 non-null    str
 15  language             409 non-null    str
 16  source_name          409 non-null    str
 17  source_url           372 non-null    str
 18  last_updated         409 non-null    str
 19  word_count           409 non-null    int64
 20  reading_level_score  396 non-null    float64
 21  evidence_level       409 non-null    str
 22  review_status        409 non-null    str
dtypes: float64(1), int64(1), str(21)
memory usage: 73.6 KB

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["doc_id"].duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

doc_id                  0
title                   0
category                0
icd10_code              0
document_type           0
content_text            0
symptoms                0
treatments              0
risk_factors            0
prevention              0
common_age_group        0
severity_level          0
is_chronic              0
is_contagious           0
target_audience         0
language                0
source_name             0
source_url             37
last_updated            0
word_count              0
reading_level_score    13
evidence_level          0
review_status           0
dtype: int64

In [12]:
df[[
    "title",
    "content_text",
    "symptoms",
    "treatments",
    "risk_factors",
    "prevention"
]].head(3)

,title,content_text,symptoms,treatments,risk_factors,prevention
0,Conjunctivitis (Pink Eye) - Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub..."
1,Urinary Tract Infection - Clinical Decision Su...,Clinical decision support summary for Urinary ...,"Strong, persistent urge to urinate; burning se...","Short course of antibiotics (e.g., nitrofurant...",Female anatomy; sexual activity; certain types...,"Adequate hydration, urinating after intercours..."
2,What are the common symptoms of Major Depressi...,Q: What are the common symptoms of Major Depre...,Persistent sad or empty mood; loss of interest...,"Psychotherapy (cognitive behavioral therapy, i...",Family history of depression; history of traum...,"Stress management, strong social support netwo..."

In [13]:
df["content_text"].str.len().describe()

count    409.000000
mean     272.845966
std      148.942064
min       87.000000
25%      168.000000
50%      223.000000
75%      321.000000
max      915.000000
Name: content_text, dtype: float64

In [14]:
df["document_type"].value_counts()

document_type
FAQ                    251
Symptom Guide           32
Treatment Guideline     32
Prevention Guide        32
Clinical Summary        31
Disease Overview        31
Name: count, dtype: int64

In [15]:
df["content_text"].str.strip().str.len().describe()

count    409.000000
mean     272.845966
std      148.942064
min       87.000000
25%      168.000000
50%      223.000000
75%      321.000000
max      915.000000
Name: content_text, dtype: float64

In [16]:
df["content_text"].str.strip().eq("").sum()

np.int64(0)

In [17]:
df["title"].nunique()

409

In [18]:
df["category"].value_counts()

category
Infectious          65
Respiratory         53
Neurological        40
Cardiovascular      39
Gastrointestinal    39
Endocrine           28
Musculoskeletal     28
Mental Health       26
Dermatologic        26
Ophthalmologic      13
Immunologic         13
Hematologic         13
Renal               13
Metabolic           13
Name: count, dtype: int64

In [19]:
clean_df = df.copy()

In [20]:
text_columns = clean_df.select_dtypes(include="object").columns

for column in text_columns:
    clean_df[column] = clean_df[column].str.strip()

C:\Users\DELL\AppData\Local\Temp\ipykernel_14176\3360080278.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = clean_df.select_dtypes(include="object").columns

In [21]:
clean_df.shape

(409, 23)

In [22]:
clean_df.isnull().sum()

doc_id                  0
title                   0
category                0
icd10_code              0
document_type           0
content_text            0
symptoms                0
treatments              0
risk_factors            0
prevention              0
common_age_group        0
severity_level          0
is_chronic              0
is_contagious           0
target_audience         0
language                0
source_name             0
source_url             37
last_updated            0
word_count              0
reading_level_score    13
evidence_level          0
review_status           0
dtype: int64

In [23]:
clean_df = df.copy()

In [24]:
text_columns = clean_df.select_dtypes(include="object").columns

for column in text_columns:
    clean_df[column] = clean_df[column].str.strip()

C:\Users\DELL\AppData\Local\Temp\ipykernel_14176\3360080278.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = clean_df.select_dtypes(include="object").columns

In [25]:
clean_df.to_csv("../data/cleaned/healthcare_cleaned.csv", index=False)

In [26]:
import os

os.path.exists("../data/cleaned/healthcare_cleaned.csv")

True

In [27]:
clean_df.shape

(409, 23)

In [28]:
clean_df.head(2)

,doc_id,title,category,icd10_code,document_type,content_text,symptoms,treatments,risk_factors,prevention,...,is_contagious,target_audience,language,source_name,source_url,last_updated,word_count,reading_level_score,evidence_level,review_status
0,DOC-E6C0C42D,Conjunctivitis (Pink Eye) - Symptom Guide,Ophthalmologic,H10,Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub...",...,Yes,Patient Education,en,CDC - Conjunctivitis,https://www.cdc.gov/conjunctivitis/index.html,2025-11-05,45,7.1,C,Peer-Reviewed
1,DOC-044236DE,Urinary Tract Infection - Clinical Decision Su...,Infectious,N39,Clinical Summary,Clinical decision support summary for Urinary ...,"Strong, persistent urge to urinate; burning se...","Short course of antibiotics (e.g., nitrofurant...",Female anatomy; sexual activity; certain types...,"Adequate hydration, urinating after intercours...",...,No,Clinician,en,NIDDK - Urinary Tract Infections,https://www.niddk.nih.gov/health-information/u...,2024-05-29,75,18.0,A,Peer-Reviewed

In [29]:
clean_df = pd.read_csv("../data/cleaned/healthcare_cleaned.csv")

In [30]:
clean_df.head(1)

,doc_id,title,category,icd10_code,document_type,content_text,symptoms,treatments,risk_factors,prevention,...,is_contagious,target_audience,language,source_name,source_url,last_updated,word_count,reading_level_score,evidence_level,review_status
0,DOC-E6C0C42D,Conjunctivitis (Pink Eye) - Symptom Guide,Ophthalmologic,H10,Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub...",...,Yes,Patient Education,en,CDC - Conjunctivitis,https://www.cdc.gov/conjunctivitis/index.html,2025-11-05,45,7.1,C,Peer-Reviewed

In [31]:
row = clean_df.iloc[0]

In [32]:
row

doc_id                                                      DOC-E6C0C42D
title                          Conjunctivitis (Pink Eye) - Symptom Guide
category                                                  Ophthalmologic
icd10_code                                                           H10
document_type                                              Symptom Guide
content_text           Patients with Conjunctivitis (Pink Eye) common...
symptoms               Redness in the white of the eye; increased tea...
treatments             Viral conjunctivitis is managed with supportiv...
risk_factors           Close contact with infected individuals; aller...
prevention             Frequent handwashing, avoiding touching or rub...
common_age_group                            All ages, common in children
severity_level                                                      Mild
is_chronic                                                            No
is_contagious                                                        Yes
target_audience                                        Patient Education
language                                                              en
source_name                                         CDC - Conjunctivitis
source_url                 https://www.cdc.gov/conjunctivitis/index.html
last_updated                                                  2025-11-05
word_count                                                            45
reading_level_score                                                  7.1
evidence_level                                                         C
review_status                                              Peer-Reviewed
Name: 0, dtype: object

In [33]:
document_text = f"""
Title: {row['title']}

Content:
{row['content_text']}

Symptoms:
{row['symptoms']}

Treatments:
{row['treatments']}

Risk Factors:
{row['risk_factors']}

Prevention:
{row['prevention']}
"""

In [34]:
print(document_text)

Title: Conjunctivitis (Pink Eye) - Symptom Guide

Content:
Patients with Conjunctivitis (Pink Eye) commonly present with the following symptoms: Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids. Symptom severity and combination vary by individual and disease stage.

Symptoms:
Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids

Treatments:
Viral conjunctivitis is managed with supportive care (cool compresses, artificial tears). Bacterial conjunctivitis may require antibiotic eye drops. Allergic conjunctivitis is treated with antihistamine eye drops.

Risk Factors:
Close contact with infected individuals; allergies; contact lens use; exposure to irritants; recent upper respiratory infection

Prevention:
Frequent handwashing, avoiding touching or rubbing the eyes, not sharing personal items such as towels, and proper contact lens hygiene.

In [35]:
metadata = {
    "doc_id": row["doc_id"],
    "category": row["category"],
    "icd10_code": row["icd10_code"],
    "document_type": row["document_type"],
    "source_name": row["source_name"],
    "source_url": row["source_url"],
    "evidence_level": row["evidence_level"],
    "review_status": row["review_status"]
}

In [36]:
metadata

{'doc_id': 'DOC-E6C0C42D',
 'category': 'Ophthalmologic',
 'icd10_code': 'H10',
 'document_type': 'Symptom Guide',
 'source_name': 'CDC - Conjunctivitis',
 'source_url': 'https://www.cdc.gov/conjunctivitis/index.html',
 'evidence_level': 'C',
 'review_status': 'Peer-Reviewed'}

In [37]:
def create_document(row):
    document_text = f"""
Title: {row['title']}

Content:
{row['content_text']}

Symptoms:
{row['symptoms']}

Treatments:
{row['treatments']}

Risk Factors:
{row['risk_factors']}

Prevention:
{row['prevention']}
"""

    metadata = {
        "doc_id": row["doc_id"],
        "category": row["category"],
        "icd10_code": row["icd10_code"],
        "document_type": row["document_type"],
        "source_name": row["source_name"],
        "source_url": row["source_url"],
        "evidence_level": row["evidence_level"],
        "review_status": row["review_status"]
    }

    return {
        "page_content": document_text,
        "metadata": metadata
    }

In [38]:
document = create_document(clean_df.iloc[0])

In [39]:
document

{'page_content': '\nTitle: Conjunctivitis (Pink Eye) - Symptom Guide\n\nContent:\nPatients with Conjunctivitis (Pink Eye) commonly present with the following symptoms: Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids. Symptom severity and combination vary by individual and disease stage.\n\nSymptoms:\nRedness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids\n\nTreatments:\nViral conjunctivitis is managed with supportive care (cool compresses, artificial tears). Bacterial conjunctivitis may require antibiotic eye drops. Allergic conjunctivitis is treated with antihistamine eye drops.\n\nRisk Factors:\nClose contact with infected individuals; allergies; contact lens use; exposure to irritants; recent upper respiratory infection\n\nPrevention:\nFrequent handwashing, avoiding touching or rubbing the eyes, not sharing personal items such as towels, and proper contact lens hygiene.\n',
 'metadata': {'doc_id': 'DOC-E6C0C42D',
  'category': 'Ophthalmologic',
  'icd10_code': 'H10',
  'document_type': 'Symptom Guide',
  'source_name': 'CDC - Conjunctivitis',
  'source_url': 'https://www.cdc.gov/conjunctivitis/index.html',
  'evidence_level': 'C',
  'review_status': 'Peer-Reviewed'}}

In [40]:
documents = []

for _, row in clean_df.iterrows():
    document = create_document(row)
    documents.append(document)

In [41]:
len(documents)

409

In [42]:
documents[0]

{'page_content': '\nTitle: Conjunctivitis (Pink Eye) - Symptom Guide\n\nContent:\nPatients with Conjunctivitis (Pink Eye) commonly present with the following symptoms: Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids. Symptom severity and combination vary by individual and disease stage.\n\nSymptoms:\nRedness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids\n\nTreatments:\nViral conjunctivitis is managed with supportive care (cool compresses, artificial tears). Bacterial conjunctivitis may require antibiotic eye drops. Allergic conjunctivitis is treated with antihistamine eye drops.\n\nRisk Factors:\nClose contact with infected individuals; allergies; contact lens use; exposure to irritants; recent upper respiratory infection\n\nPrevention:\nFrequent handwashing, avoiding touching or rubbing the eyes, not sharing personal items such as towels, and proper contact lens hygiene.\n',
 'metadata': {'doc_id': 'DOC-E6C0C42D',
  'category': 'Ophthalmologic',
  'icd10_code': 'H10',
  'document_type': 'Symptom Guide',
  'source_name': 'CDC - Conjunctivitis',
  'source_url': 'https://www.cdc.gov/conjunctivitis/index.html',
  'evidence_level': 'C',
  'review_status': 'Peer-Reviewed'}}

In [43]:
documents[1]["metadata"]

{'doc_id': 'DOC-044236DE',
 'category': 'Infectious',
 'icd10_code': 'N39',
 'document_type': 'Clinical Summary',
 'source_name': 'NIDDK - Urinary Tract Infections',
 'source_url': 'https://www.niddk.nih.gov/health-information/urologic-diseases/bladder-infection-uti-in-adults',
 'evidence_level': 'A',
 'review_status': 'Peer-Reviewed'}